name: Daily_Model_Training

on:
  schedule:
    - cron: '0 0 * * *' # Runs exactly at midnight UTC every day
  workflow_dispatch:      # Allows you to trigger it manually for testing

jobs:
  train_and_predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # Speeds up subsequent runs

      - name: Install Dependencies
        run: |
          pip install pandas requests xgboost scikit-learn joblib hopsworks
          # We explicitly avoid installing pyarrow here if it was causing issues, 
          # but Hopsworks usually requires it as a dependency. 

      - name: Run Training Pipeline
        env:
          MY_HOPSWORK_KEY: ${{ secrets.MY_HOPSWORKS_KEY }}
          # This flag tells Hopsworks NOT to use the Arrow Flight server for reading data
          # It forces the use of the standard REST API / Online Store client
          HSFS_DISABLE_FLIGHT_CLIENT: "True" 
        run: python pipelines/training_pipeline.py
