name: Daily_Training_Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install "hopsworks[python]" pandas xgboost scikit-learn joblib pyarrow

      - name: Run Training Pipeline
        env:
          MY_HOPSWORK_KEY: ${{ secrets.MY_HOPSWORKS_KEY }}
          # THIS IS THE MAGIC LINE TO STOP THE ERROR:
          HSFS_DISABLE_REST_DATA_INTERFACE: "true"
        run: python pipelines/training_pipeline.py
