name: Hourly_Data_Fetcher

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:      # Add a manual start button

jobs:
  run_fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install "hopsworks[python]" pandas requests xgboost scikit-learn joblib pyarrow confluent-kafka

      - name: Run Python Script with Retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: python pipelines/fetch_live_data_hourly.py
        env:
          MY_HOPSWORK_KEY: ${{ secrets.MY_HOPSWORKS_KEY }}
