name: Hourly_Data_Fetcher
on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:      # Add a manual start button
jobs:
  run_fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Libraries
        run: pip install hopsworks pandas requests xgboost scikit-learn joblib pyarrow
      - name: Run Python Script
        env:
          MY_HOPSWORK_KEY: ${{ secrets.MY_HOPSWORKS_KEY }}
        run: python pipelines/fetch_live_data_hourly.py
